### ISSUE TITLE
Remove this Plugin!

### ISSUE THREAD

**Issue by TheBalkanDev** [FukkitX/GaySexLegends#2]
This Plugin don‘t have to be here.
Nobody needs and it’s not for the Public.
This Plugin is very disgusting!
You can use it for you but NOT HERE ON GITHUB!

I give you 7 Days to delete this, or I will report you on GitHub and Poggit.

**Comment by TacoNoBurrito** [comment]
shut the fuck up. i swear to god

**Comment by BoomYourBang** [comment]
you're mom

**Comment by Prim69** [comment]
report it lmao id love for a github mod to react to gay sex legends!

**Comment by ItsViper** [comment]
shut up fat retard

**Comment by CodsXBlastin** [comment]
dirty coon boy wont hush up stay mad random L dance cum in your boxers can handle the sex mod

**Comment by TheBalkanDev** [comment]
So... well well well...

**Comment by TheBalkanDev** [comment]
You have 5 days time to delete it, or I will report this and your Account will be deleted.

** I don’t say twice**

**Comment by TheBalkanDev** [comment]
@CodsXBlastin  WTF

**Comment by ItsViper** [comment]
@TheBalkanDev your a fat retard 6 year old faggot. Yo ass don't even speak correctly fucking allah uk bar head ass. Shut your mouth fat retard.

**Comment by TheBalkanDev** [comment]
@TacoNoBurrito Nope I don’t shut up you should shut up an people like you don’t have the permission to swear on God

**Comment by TheBalkanDev** [comment]
@ItsViper lol I am 21

**Comment by ItsViper** [comment]
@TheBalkanDev that's such a lie. You a fat retarded monk ong. Allah uk bar head ass mf. 21 my ass!!

**Comment by TheBalkanDev** [comment]
@ItsViper I don’t think that I asked for your opinion

**Comment by TheBalkanDev** [comment]
@ItsViper I will report sou too when you don’t shut up! OKAY

**Comment by CodsXBlastin** [comment]
Chat more shit random and your going off no cap on gang

**Comment by TheBalkanDev** [comment]
So I’ve reported this Plugin and 2 users

**Comment by Prim69** [comment]
You're 21 and are throwing a fit over a minecraft sex plugin? Damn.

**Comment by ItsViper** [comment]
> @ItsViper I will report sou too when you don’t shut up! OKAY

shut your mouth fat retard

**Comment by TheBalkanDev** [comment]
Yes, right

**Comment by ItsViper** [comment]
> So I’ve reported this Plugin and 2 users

I am reporting you as-well, i will send git hub proof of you sex trafficking little indonesion girls on the dark inter web. Good luck 👍

**Comment by ItsViper** [comment]
you type like a mentally impaired moron 😂

**Comment by TheBalkanDev** [comment]
Thanks, I will send this comment too

**Comment by TheBalkanDev** [comment]
No my English is not the best sou can speak  Romanian or German? No I don’t think so

**Comment by TacoNoBurrito** [comment]
you fucking idiot degenerate fucking dong sucker child fucker rapist shut up useless fuck you will never amount to anything in life

**Comment by CodsXBlastin** [comment]
@TheBalkanDev Ich werde deine Mutter trocknen, bis sie auseinander fällt, dann werde ich die Asche ficken, in die sie sich verwandelt hat, dann die Asche zu Essen machen und sie essen und dann auf dein Grab scheißen, nachdem du gestorben bist

**Comment by TheBalkanDev** [comment]
@CodsXBlastin ähmm, dat geht ned mit was willstn F*cken? Weil 3mm gehn ned dat weißt du aber auch ganz genau

**Comment by ItsViper** [comment]
@TheBalkanDev Sie sind geistig zurückgeblieben. Bitte löschen Sie Zwietracht und erhalten Sie ein Leben: p

**Comment by TheBalkanDev** [comment]
@ItsViper Please don’t use Google Translator its territory German

**Comment by CodsXBlastin** [comment]
@TheBalkanDev Hör zu, du weißt nicht, wie du deinen schwulen Arsch buchstabieren sollst

**Comment by TheBalkanDev** [comment]
Wat für schwul digga

**Comment by CodsXBlastin** [comment]
hushmode random racist

**Comment by TheBalkanDev** [comment]
Uff lost

**Comment by xSuperr** [comment]
LMFAO THIS KID IS WEIRD

**Comment by Cqdet** [comment]
virgin squad has assembled

**Comment by ethaniccc** [comment]
Gay sex legends, assemble!

**Comment by TheBalkanDev** [comment]
All are dumm

**Comment by ethaniccc** [comment]
Couldn't take it down stay mad L

**Comment by Cqdet** [comment]
so this is how php mentally deprives brain cells in a human... ic
